name       : opencollada
version    : 1.6.68
release    : 1
source     :
    - https://github.com/KhronosGroup/OpenCOLLADA/archive/v1.6.68.tar.gz : d9db0c0a518aa6ac0359626f222707c6ca1b63a83cbf229d97a5999c9cde347b
license    : MIT
component  : multimedia.library
summary    : COLLADA (COLLAborative Design Activity) is an interchange file format for interactive 3D applications.
description: |
    COLLADA defines an open standard XML schema for exchanging digital assets among various graphics software applications that might otherwise store their assets in incompatible file formats. COLLADA documents that describe digital assets are XML files, usually identified with a .dae (digital asset exchange) filename extension.

    It is managed by the nonprofit technology consortium, the Khronos Group, and has been adopted by ISO as a publicly available specification, ISO/PAS 17506.
builddeps  :
    - pkgconfig(libpcre)
    - pkgconfig(libxml-2.0)
setup      : |
    patch -p1 -i $pkgfiles/fix-build-with-newer-pcre.patch

    %cmake_ninja -DUSE_STATIC=OFF -DUSE_SHARED=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    # ensure that the opencollada libs can be found
    install -m 0644 -D $pkgfiles/opencollada.ld.so.conf $installdir/usr/share/ld.so.conf.d/opencollada.conf